object_type = "item"
id = "campfire"
 
[image]
copyright="T.Okubo"
path = "campfire.png"

[item]
item_kind = "object"
group = "facility"
gen_weight = 0
gen_level = 0
basic_price = 1480
w = 5500
facility = ["stove", -2]
