object_type = "item"
id = "drug-lab"
 
[image]
copyright="T.Okubo"
path = "drug-lab.png"

[item]
item_kind = "object"
group = "facility"
gen_weight = 0
gen_level = 0
basic_price = 4300
w = 6000
facility = ["pharmacy", 0]
