object_type = "item"
id = "stone-furnance"
 
[image]
copyright="T.Okubo"
path = "stone-furnance.png"

[item]
item_kind = "object"
group = "facility"
gen_weight = 0
gen_level = 0
basic_price = 1480
w = 5500
facility = ["furnance", 0]
