object_type = "item"
id = "stove"
 
[image]
copyright="T.Okubo"
path = "stove.png"

[item]
item_kind = "object"
group = "facility"
gen_weight = 0
gen_level = 0
basic_price = 540
w = 80000
facility = "stove"
