object_type = "chara_template"
id = "guild-informant"
 
[image]
copyright="T.Okubo"
path = "guild-informant.png"
w = 24
h = 48

[chara_template]
race = "human"
gen_weight = 0
gen_level = 0
default_ai_kind = "wander"
base_hp = 100
str = 20
vit = 22
dex = 24
int = 24
wil = 17
cha = 19
spd = 100
