object_type = "chara_template"
id = "shopkeeper-m-1"
 
[image]
copyright="T.Okubo"
path = "shopkeeper-m-1.png"
w = 24
h = 48

[chara_template]
race = "human"
gen_weight = 0
gen_level = 0
default_ai_kind = "wander"
base_hp = 120
str = 14
vit = 20
dex = 22
int = 20
wil = 11
cha = 17
spd = 100
