object_type = "chara_template"
id = "!towngirl.1"
 
[image]
path = "towngirl.1.png"
w = 24
h = 48

[chara_template]
race = "Human"
gen_weight = 0
gen_level = 0
max_hp = 100
str = 12
vit = 16
dex = 15
int = 15
wil = 12
cha = 18
spd = 100
