object_type = "chara_template"
id = "towngirl-1"
 
[image]
copyright="T.Okubo"
path = "towngirl-1.png"
w = 24
h = 48

[chara_template]
race = "human"
gen_weight = 0
gen_level = 0
default_ai_kind = "wander"
base_hp = 70
str = 12
vit = 16
dex = 15
int = 15
wil = 12
cha = 18
spd = 100
