object_type = "item"
id = "live-oak-01"

[image]
copyright="T.Okubo"
path = "live-oak-01.png"

[item]
item_kind = "object"
group = "tree"
gen_weight = 0
gen_level = 0
basic_price = 100
w = 2000000

[item.harvest]
harvest_type = "chop"
target_item = "wood"
difficulty = 0
n_yield = 80
