object_type = "item"
id = "saguaro-01"

[image]
copyright="T.Okubo"
path = "saguaro-01.png"

[item]
item_kind = "object"
gen_weight = 0
gen_level = 0
basic_price = 100
w = 100000

[item.harvest]
harvest_type = "chop"
target_item = "plank"
difficulty = 0
n_yield = 15
