object_type = "item"
id = "torch-arrow"
 
[image]
copyright="T.Okubo"
path = "torch-arrow.png"

[item]
item_kind = "magic_device"
group = "torch"
gen_weight = 20
gen_level = 0
basic_price = 2000
w = 600
charge = [8, 16]
dice_n = 5
dice_x = 10

[item.magical_effect]
range = 7
anim_kind = "shot"
anim_img_shot = "magic-arrow-physical"

[[item.magical_effect.kind]]
kind = "ranged"
element = "physical"
