object_type = "item"
id = "tricorder"
 
[image]
copyright="T.Okubo"
path = "tricorder.png"

[item]
item_kind = "magic_device"
group = "scan"
gen_weight = 10
gen_level = 3
basic_price = 4000
w = 600
charge = [15, 20]
eff = 100

[item.magical_effect]
range = 4
anim_img = "scan-chara"
sound = "scan-chara"

[[item.magical_effect.kind]]
kind = "status"
status = "scanned"
