object_type = "item"
id = "longbow"
 
[image]
copyright="T.Okubo"
path = "longbow.png"

[item]
item_kind = "weapon"
group = "bow"
gen_weight = 3
gen_level = 1
basic_price = 300
w = 1000
quality_kind = "mutable"

weapon_kind = "bow"
eff = 8
eff_var = 4
material_group = "wood"
