object_type = "item"
id = "shortbow"
 
[image]
copyright="T.Okubo"
path = "shortbow.png"

[item]
item_kind = "weapon"
group = "bow"
gen_weight = 3
gen_level = 1
basic_price = 40
w = 600
quality_kind = "mutable"

weapon_kind = "bow"
dice_n = 2
dice_x = 2
material_group = "wood"
