object_type = "item"
id = "copper-plate"
 
[image]
copyright="T.Okubo"
path = "copper-plate.png"

[item]
item_kind = "material"
group = "metal"
gen_weight = 10
gen_level = 1
basic_price = 800
w = 1150
material = "copper"
