object_type = "item"
id = "granite-block"
 
[image]
copyright="T.Okubo"
path = "granite-block.png"

[item]
item_kind = "material"
group = "stone-material"
gen_weight = 1
gen_level = 1
basic_price = 100
w = 5000
material = "granite"
