object_type = "item"
id = "iron"
 
[image]
copyright="T.Okubo"
path = "iron.png"

[item]
item_kind = "material"
group = "metal"
gen_weight = 10
gen_level = 4
basic_price = 200
w = 2000
material = "iron"
