object_type = "item"
id = "steel-plate"
 
[image]
copyright="T.Okubo"
path = "steel-plate.png"

[item]
item_kind = "material"
group = "metal"
gen_weight = 10
gen_level = 1
basic_price = 1000
w = 1000
