object_type = "item"
id = "wood"
 
[image]
copyright="T.Okubo"
path = "wood.png"

[item]
item_kind = "material"
group = "wood"
gen_weight = 10
gen_level = 1
basic_price = 10
w = 1500
material = "wood"
