object_type = "item"
id = "small-sculpture"
 
[image]
copyright="T.Okubo"
path = "small-sculpture.png"
w = 32
h = 32
grid_nx = 3
grid_ny = 1
n_pattern = 3
variation_rule = "random_on_gen"

[item]
item_kind = "object"
group = "art"
gen_weight = 0
gen_level = 0
basic_price = 5000
w = 15000
