object_type = "item"
id = "!bronze-dagger"
 
[image]
path = "bronze-dagger.png"

[item]
gen_weight = 7
gen_level = 1
basic_price = 100

item_kind = "Weapon"
weapon_kind = "Sword"
dice_n = 4
dice_x = 2
