object_type = "item"
id = "!bronze-spear"
 
[image]
path = "bronze-spear.png"

[item]
gen_weight = 5
gen_level = 2
basic_price = 180

item_kind = "Weapon"
weapon_kind = "Spear"
dice_n = 2
dice_x = 10
