object_type = "item"
id = "bronze-spear"
 
[image]
copyright="T.Okubo"
path = "bronze-spear.png"

[item]
item_kind = "weapon"
group = "spear"
gen_weight = 5
gen_level = 2
basic_price = 180
w = 7000

weapon_kind = "spear"
eff = 20
