object_type = "item"
id = "iron-revolver"
 
[image]
copyright="T.Okubo"
path = "iron-revolver.png"

[item]
item_kind = "weapon"
gen_weight = 1
gen_level = 10
basic_price = 3000
w = 400

weapon_kind = "firearm"
dice_n = 2
dice_x = 10
