object_type = "item"
id = "steel-whip"
 
[image]
copyright="T.Okubo"
path = "steel-whip.png"

[item]
item_kind = "weapon"
group = "whip"
gen_weight = 2
gen_level = 7
basic_price = 220
w = 5000

weapon_kind = "whip"
eff = 15
