object_type = "item"
id = "steel-spear"
 
[image]
copyright="T.Okubo"
path = "steel-spear.png"

[item]
item_kind = "weapon"
group = "spear"
gen_weight = 5
gen_level = 9
basic_price = 350
w = 7000

weapon_kind = "spear"
dice_n = 2
dice_x = 20
