object_type = "item"
id = "!steel-sword"
 
[image]
path = "steel-sword.png"

[item]
item_kind = "weapon"
gen_weight = 5
gen_level = 10
basic_price = 1400

weapon_kind = "sword"
dice_n = 2
dice_x = 12
