object_type = "item"
id = "!steel-longbow"
 
[image]
path = "steel-longbow.png"

[item]
item_kind = "weapon"
gen_weight = 3
gen_level = 12
basic_price = 1500

weapon_kind = "bow"
dice_n = 2
dice_x = 5
