object_type = "item"
id = "steel-dagger"
 
[image]
copyright="T.Okubo"
path = "steel-dagger.png"

[item]
item_kind = "weapon"
group = "dagger"
gen_weight = 7
gen_level = 8
basic_price = 220
w = 1000

weapon_kind = "sword"
dice_n = 4
dice_x = 4
