object_type = "item"
id = "steel-longbow"
 
[image]
copyright="T.Okubo"
path = "steel-longbow.png"

[item]
item_kind = "weapon"
group = "bow"
gen_weight = 3
gen_level = 12
basic_price = 1500
w = 2500

weapon_kind = "bow"
dice_n = 2
dice_x = 5
