object_type = "item"
id = "wood-longbow"
 
[image]
copyright="T.Okubo"
path = "wood-longbow.png"

[item]
item_kind = "weapon"
group = "bow"
gen_weight = 3
gen_level = 1
basic_price = 300
w = 1000

weapon_kind = "bow"
dice_n = 2
dice_x = 2
