object_type = "wall"
id = "wooden-wall-01"

[image]
copyright="T.Okubo"
path = "wooden-wall-01.png"
w = 48
h = 80
grid_nx = 3
grid_ny = 2
n_pattern = 5

[wall]
build_skill = 1
materials = [["plank", 10]]
