object_type = "chara_template"
id = "armadillo"
 
[image]
copyright="T.Okubo"
path = "armadillo.png"

[chara_template]
race = "animal"
gen_weight = 100
gen_level = 1
default_ai_kind = "melee"
base_hp = 110
str = 15
vit = 18
dex = 12
int = 12
wil = 12
cha = 17
spd = 100
