object_type = "chara_template"
id = "!cockatrice"
 
[image]
path = "cockatrice.png"
w = 32
h = 48

[chara_template]
race = "animal"
gen_weight = 20
gen_level = 22
max_hp = 76
str = 24
vit = 17
dex = 16
int = 20
wil = 15
cha = 20
spd = 100
