object_type = "chara_template"
id = "cockatrice"
 
[image]
copyright="T.Okubo"
path = "cockatrice.png"
w = 32
h = 48

[chara_template]
race = "animal"
gen_weight = 100
gen_level = 22
default_ai_kind = "melee"
base_hp = 85
str = 24
vit = 17
dex = 16
int = 20
wil = 15
cha = 20
spd = 100
