object_type = "chara_template"
id = "emu"
 
[image]
copyright="T.Okubo"
path = "emu.png"

[chara_template]
race = "animal"
gen_weight = 100
gen_level = 14
default_ai_kind = "melee"
base_hp = 90
str = 20
vit = 14
dex = 13
int = 16
wil = 15
cha = 18
spd = 100
