object_type = "chara_template"
id = "llama"
 
[image]
copyright="T.Okubo"
path = "llama.png"

[chara_template]
race = "animal"
gen_weight = 50
gen_level = 1
default_ai_kind = "melee"
base_hp = 150
str = 18
vit = 22
dex = 11
int = 10
wil = 12
cha = 14
spd = 100
