object_type = "chara_template"
id = "!mouse"
 
[image]
path = "mouse.png"
w = 24
h = 12

[chara_template]
race = "animal"
gen_weight = 20
gen_level = 1
max_hp = 22
str = 14
vit = 14
dex = 13
int = 8
wil = 11
cha = 9
spd = 110
