object_type = "chara_template"
id = "!stray-dog"
 
[image]
path = "stray-dog.png"
w = 24
h = 28

[chara_template]
race = "Animal"
gen_weight = 30
gen_level = 4
max_hp = 24
str = 16
vit = 14
dex = 10
int = 10
wil = 12
cha = 10
spd = 100
