object_type = "item"
id = "bookshelf-01"
 
[image]
copyright="T.Okubo"
path = "bookshelf-01.png"
w = 48
h = 48

[item]
item_kind = "object"
group = "furniture"
gen_weight = 0
gen_level = 0
basic_price = 3400
w = 28000
