object_type = "item"
id = "bunk-bed-01"
 
[image]
copyright="T.Okubo"
path = "bunk-bed-01.png"

[item]
item_kind = "object"
group = "furniture"
gen_weight = 0
gen_level = 0
basic_price = 1500
w = 90000
