object_type = "item"
id = "chair-01"
 
[image]
copyright="T.Okubo"
path = "chair-01.png"
w = 48
h = 48

[item]
item_kind = "object"
group = "furniture"
gen_weight = 0
gen_level = 0
basic_price = 400
w = 1500
