object_type = "item"
id = "cupboard-01"
 
[image]
copyright="T.Okubo"
path = "cupboard-01.png"
w = 48
h = 48

[item]
item_kind = "object"
group = "furniture"
gen_weight = 0
gen_level = 0
basic_price = 3000
w = 22000
