object_type = "item"
id = "gas-cylinders-01"
 
[image]
copyright="T.Okubo"
path = "gas-cylinders-01.png"

[item]
item_kind = "object"
group = "furniture"
gen_weight = 0
gen_level = 0
basic_price = 1200
w = 60000
