object_type = "item"
id = "juke-box-01"
 
[image]
copyright="T.Okubo"
path = "juke-box-01.png"

[item]
item_kind = "object"
group = "furniture"
gen_weight = 2
gen_level = 2
basic_price = 120000
w = 55000
