object_type = "item"
id = "oscilloscope-01"
 
[image]
copyright="T.Okubo"
path = "oscilloscope-01.png"

[item]
item_kind = "object"
group = "furniture"
gen_weight = 0
gen_level = 0
basic_price = 20000
w = 5000
