object_type = "item"
id = "plant-pot-01"
 
[image]
copyright="T.Okubo"
path = "plant-pot-01.png"

[item]
item_kind = "object"
group = "furniture"
gen_weight = 0
gen_level = 0
basic_price = 240
w = 1400
