object_type = "item"
id = "research-table-01"
 
[image]
copyright="T.Okubo"
path = "research-table-01.png"

[item]
item_kind = "object"
group = "furniture"
gen_weight = 0
gen_level = 0
basic_price = 4000
w = 25000
