object_type = "item"
id = "resurrect-reactor-01"
 
[image]
copyright="T.Okubo"
path = "resurrect-reactor-01.png"

[item]
item_kind = "object"
group = "furniture"
gen_weight = 0
gen_level = 0
basic_price = 1000000
w = 300000
