object_type = "script"
id = "prof"

[script]
script = """
--- start
jump_if(has-box, has_item(ancient-box))
talk(prof.0)
--- has-box
talk(prof.1,
     [(ans.yes, continue), (ans.no, after-no)])
recieve_money(1000)
remove_item(ancient-box)
talk(prof.2)
--- after-no
talk(prof.3)
"""

