object_type = "script"
id = "prof"

[script]
script = """
--- start
jump_if(collected-3, $(given-ancient-box) == 3)
jump_if(has-box, has_item(ancient-box))
talk(prof.0)
--- has-box
talk(prof.1,
     [(ans.yes, continue), (ans.no, after-no)])
recieve_money(1000)
gset(given-ancient-box, $(given-ancient-box) + 1)
remove_item(ancient-box)
talk(prof.2)
--- after-no
talk(prof.3)
--- collected-3
talk(prof.4)
"""
