object_type = "region_gen"
id = "south-coast"

[region_gen]
map_template_id = "south-coast"

[[region_gen.towns]]
id = "town-freedom"
pos = [44, 48]

[[region_gen.others]]
id = "institute-of-life-sciences"
pos = [21, 42]
