object_type = "chara_template"
id = "magma-slime"
 
[image]
path = "magma-slime.png"
w = 24
h = 48

[chara_template]
race = "slime"
gen_weight = 10
gen_level = 18
max_hp = 80
str = 18
vit = 18
dex = 12
int = 8
wil = 5
cha = 10
spd = 75
