object_type = "site_gen"
id = "town-freedom"

[site_gen]
kind = "town"
map_template_id = ["town-freedom-0"]

[[site_gen.unique_citizens]]
pos = [3, 3]
floor = 0
chara_template_id = "guild-informant"
talk_script_id = "guild-informant"

[[site_gen.unique_citizens]]
pos = [3, 12]
floor = 0
chara_template_id = "towngirl-1"
talk_script_id = "hello"

[[site_gen.unique_citizens]]
pos = [10, 10]
floor = 0
chara_template_id = "u-captain"
talk_script_id = "u-captain"

[[site_gen.unique_citizens]]
pos = [7, 4]
floor = 0
chara_template_id = "shopkeeper-m-1"
talk_script_id = "shop"

[[site_gen.shops]]
floor = 0
kind = "equipment"
