object_type = "item"
id = "herb-aconitum"
 
[image]
copyright="T.Okubo"
path = "aconitum.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 10
gen_level = 0
basic_price = 20
w = 20

medical_effect= "poison"
eff = 10
nutrition = 10
