object_type = "item"
id = "herb-aconitum"
 
[image]
copyright="T.Okubo"
path = "aconitum.png"

[item]
item_kind = "food"
group = "herb"
gen_weight = 10
gen_level = 0
basic_price = 20
w = 20
eff = 10
nutrition = 10

[[item.medical_effect.kind]]
kind = "status"
status = "poison"
