object_type = "item"
id = "herb-medical_herb"
 
[image]
copyright="T.Okubo"
path = "medical_herb.png"

[item]
item_kind = "food"
group = "herb"
gen_weight = 10
gen_level = 1
basic_price = 30
w = 15
eff = 30
nutrition = 10

[[item.medical_effect.kind]]
kind = "recover_hp"
