object_type = "item"
id = "herb.medical-herb"
 
[image]
path = "medical-herb.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 10
gen_level = 1
basic_price = 30
w = 15

medical_effect= "heal"
eff = 30
nutrition = 10
