object_type = "item"
id = "sleep-rose"
 
[image]
path = "sleep-rose.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 20
gen_level = 0
basic_price = 30
w = 20

medical_effect= "sleep"
eff = 10
nutrition = 5
