object_type = "item"
id = "herb-sleep_rose"
 
[image]
copyright="T.Okubo"
path = "sleep_rose.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 20
gen_level = 0
basic_price = 30
w = 20

medical_effect= "sleep"
eff = 10
nutrition = 5
