object_type = "item"
id = "herb-sleep_rose"
 
[image]
copyright="T.Okubo"
path = "sleep_rose.png"

[item]
item_kind = "food"
group = "herb"
gen_weight = 20
gen_level = 0
basic_price = 30
w = 20
eff = 10
nutrition = 5

[[item.medical_effect.kind]]
kind = "status"
status = "asleep"
