object_type = "item"
id = "herb-weed2"
 
[image]
copyright="T.Okubo"
path = "weed2.png"

[item]
item_kind = "food"
group = "herb"
gen_weight = 10
gen_level = 1
basic_price = 20
w = 15

medical_effect= "heal"
eff = 10
nutrition = 10
