object_type = "chara_template"
id = "prof"
 
[image]
path = "prof.png"
w = 24
h = 48

[chara_template]
race = "human"
gen_weight = 0
gen_level = 0
max_hp = 200
str = 14
vit = 20
dex = 20
int = 25
wil = 20
cha = 20
spd = 100
