object_type = "chara_template"
id = "u-captain"
 
[image]
copyright="T.Okubo"
path = "u-captain.png"
w = 24
h = 48

[chara_template]
race = "human"
gen_weight = 0
gen_level = 0
base_hp = 100
str = 24
vit = 22
dex = 20
int = 20
wil = 20
cha = 20
spd = 100
