object_type = "item"
id = "game-manual"
 
[image]
copyright="T.Okubo"
path = "game-manual.png"

[item]
item_kind = "readable"
group = "manual"
gen_weight = 100
gen_level = 0
basic_price = 200
w = 200
titles = ["game-manual"]
