object_type = "item"
id = "travel-guide"
 
[image]
copyright="T.Okubo"
path = "travel-guide.png"

[item]
item_kind = "readable"
group = "manual"
gen_weight = 100
gen_level = 0
basic_price = 200
w = 200
titles = ["geography-of-the-north-continent"]
