object_type = "item"
id = "building-hammer"
 
[image]
copyright="T.Okubo"
path = "building-hammer.png"

[item]
item_kind = "tool"
group = "tool"
gen_weight = 0
gen_level = 0
basic_price = 100
w = 500
tool_effect = "build"
