object_type = "item"
id = "pickaxe"
 
[image]
copyright="T.Okubo"
path = "pickaxe.png"

[item]
item_kind = "tool"
group = "tool"
gen_weight = 0
gen_level = 0
basic_price = 800
w = 1000
tool_effect = "mine"
