object_type = "chara_template"
id = "flying-eye"
 
[image]
path = "flying-eye.png"
w = 24
h = 48

[chara_template]
race = "ghost"
gen_weight = 12
gen_level = 10
default_ai_kind = "melee"
base_hp = 10
str = 12
vit = 11
dex = 11
int = 17
wil = 16
cha = 12
spd = 100
