object_type = "chara_template"
id = "gast"
 
[image]
copyright="T.Okubo"
path = "gast.png"
w = 24
h = 40

[chara_template]
race = "ghost"
gen_weight = 100
gen_level = 5
default_ai_kind = "melee"
base_hp = 30
str = 16
vit = 15
dex = 10
int = 14
wil = 13
cha = 11
spd = 100
