object_type = "chara_template"
id = "onibi"
 
[image]
path = "onibi.png"
w = 24
h = 24

[chara_template]
race = "ghost"
gen_weight = 15
gen_level = 1
default_ai_kind = "melee"
base_hp = 20
str = 14
vit = 12
dex = 10
int = 11
wil = 12
cha = 12
spd = 100
