object_type = "item"
id = "bronze-breastplate"
 
[image]
copyright="T.Okubo"
path = "bronze-breastplate.png"

[item]
item_kind = "armor"
gen_weight = 3
gen_level = 11
basic_price = 500
w = 5000

armor_kind = "body"
def = [6, 4, 4, 2, 2, 0]
