object_type = "item"
id = "!bronze-scalearmor"
 
[image]
path = "bronze-scalearmor.png"

[item]
gen_weight = 3
gen_level = 11
basic_price = 350

item_kind = "Armor"
armor_kind = "Body"
def = 9
mdf = 3
