object_type = "item"
id = "bronze-scalearmor"
 
[image]
copyright="T.Okubo"
path = "bronze-scalearmor.png"

[item]
item_kind = "armor"
gen_weight = 3
gen_level = 11
basic_price = 350
w = 10000

armor_kind = "body"
def = [9, 4, 4, 4, 2, 0]
