object_type = "item"
id = "!bronze-breastplate"
 
[image]
path = "bronze-breastplate.png"

[item]
item_kind = "armor"
gen_weight = 3
gen_level = 11
basic_price = 500

armor_kind = "body"
def = 6
mdf = 3
