object_type = "item"
id = "bronze-platearmor"
 
[image]
path = "bronze-platearmor.png"

[item]
item_kind = "armor"
gen_weight = 3
gen_level = 14
basic_price = 1280

armor_kind = "body"
def = 12
mdf = 5
