object_type = "item"
id = "!bronze-platearmor"
 
[image]
path = "bronze-platearmor.png"

[item]
gen_weight = 3
gen_level = 14
basic_price = 1280

item_kind = "Armor"
armor_kind = "Body"
def = 12
mdf = 5
