object_type = "item"
id = "!steel-breastplate"
 
[image]
path = "steel-breastplate.png"

[item]
gen_weight = 3
gen_level = 11
basic_price = 500

item_kind = "Armor"
armor_kind = "Body"
def = 10
mdf = 3
