object_type = "item"
id = "!steel-scalearmor"
 
[image]
path = "steel-scalearmor.png"
w = 24
h = 24

[icon]

[item]
gen_weight = 3
gen_level = 11
basic_price = 650

item_kind = "Armor"
armor_kind = "Body"
def = 13
mdf = 3
