object_type = "item"
id = "steel-scalearmor"
 
[image]
copyright="T.Okubo"
path = "steel-scalearmor.png"

[item]
item_kind = "armor"
group = "scalearmor"
gen_weight = 3
gen_level = 11
basic_price = 650
w = 10000

armor_kind = "body"
def = [13, 6, 6, 6, 3, 0]
