object_type = "item"
id = "steel-breastplate"
 
[image]
path = "steel-breastplate.png"

[item]
item_kind = "armor"
gen_weight = 3
gen_level = 11
basic_price = 500

armor_kind = "body"
def = 10
mdf = 3
