object_type = "item"
id = "steel-platearmor"
 
[image]
copyright="T.Okubo"
path = "steel-platearmor.png"

[item]
item_kind = "armor"
group = "platearmor"
gen_weight = 3
gen_level = 14
basic_price = 2280
w = 20000

armor_kind = "body"
def = [20, 10, 10, 10, 5, 0]
