object_type = "item"
id = "!steel-platearmor"
 
[image]
path = "steel-platearmor.png"
w = 24
h = 24

[icon]

[item]
gen_weight = 3
gen_level = 14
basic_price = 2280

item_kind = "Armor"
armor_kind = "Body"
def = 20
mdf = 5
