object_type = "item"
id = "steel-platearmor"
 
[image]
path = "steel-platearmor.png"
w = 24
h = 24

[item]
item_kind = "armor"
gen_weight = 3
gen_level = 14
basic_price = 2280
w = 20000

armor_kind = "body"
def = 20
mdf = 5
