object_type = "item"
id = "bokken"
 
[image]
copyright="T.Okubo"
path = "bokken.png"

[item]
item_kind = "weapon"
group = "sword"
gen_weight = 5
gen_level = 1
basic_price = 100
w = 1200
quality_kind = "mutable"

weapon_kind = "sword"
eff = 4
eff_var = 1
material_group = "wood"
