object_type = "item"
id = "bokken"
 
[image]
copyright="T.Okubo"
path = "bokken.png"

[item]
item_kind = "weapon"
group = "sword"
gen_weight = 5
gen_level = 1
basic_price = 100
w = 1200

weapon_kind = "sword"
dice_n = 4
dice_x = 1
