object_type = "item"
id = "dagger"
 
[image]
copyright="T.Okubo"
path = "dagger.png"

[item]
item_kind = "weapon"
group = "dagger"
gen_weight = 7
gen_level = 1
basic_price = 100
w = 7000
quality_kind = "mutable"

weapon_kind = "sword"
dice_n = 4
dice_x = 2
material_group = "metal"
