object_type = "item"
id = "sword"
 
[image]
copyright="T.Okubo"
path = "sword.png"

[item]
item_kind = "weapon"
group = "sword"
gen_weight = 5
gen_level = 10
basic_price = 1400
w = 4000
quality_kind = "mutable"

weapon_kind = "sword"
eff = 24
eff_var = 4
material_group = "metal"
