object_type = "chara_template"
id = "!archeologist.m"
 
[image]
path = "archeologist.m.png"
w = 24
h = 48

[chara_template]
race = "human"
gen_weight = 0
gen_level = 1
max_hp = 20
str = 15
vit = 18
dex = 26
int = 24
wil = 18
cha = 18
spd = 100
