object_type = "chara_template"
id = "archaeologist-m"
 
[image]
copyright="T.Okubo"
path = "archaeologist-m.png"
w = 24
h = 48

[chara_template]
race = "human"
gen_weight = 0
gen_level = 1
base_hp = 20
str = 15
vit = 18
dex = 26
int = 24
wil = 18
cha = 18
spd = 100
