object_type = "chara_template"
id = "sorcerer-m"
 
[image]
path = "sorcerer-m.png"
w = 24
h = 48

[chara_template]
race = "human"
gen_weight = 0
gen_level = 1
base_hp = 20
str = 14
vit = 15
dex = 18
int = 27
wil = 22
cha = 20
spd = 100
