object_type = "item"
id = "!aconitum"
 
[image]
path = "aconitum.png"
w = 24
h = 24

[icon]

[item]
gen_weight = 10
gen_level = 0
basic_price = 20

item_kind = "Food"
medical_effect= "Poison"
eff = 10
nutrition = 10
