object_type = "item"
id = "healing-potion"
 
[image]
copyright="T.Okubo"
path = "healing-potion.png"

[item]
item_kind = "potion"
group = "potion"
gen_weight = 20
gen_level = 0
basic_price = 20
w = 200

medical_effect = "heal"
eff = 30
