object_type = "item"
id = "!healing-potion"
 
[image]
path = "healing-potion.png"
w = 24
h = 24

[item]
item_kind = "potion"
gen_weight = 20
gen_level = 0
basic_price = 20

medical_effect = "heal"
eff = 30
