object_type = "item"
id = "poison"
 
[image]
copyright="T.Okubo"
path = "poison.png"

[item]
item_kind = "potion"
group = "potion"
gen_weight = 10
gen_level = 0
basic_price = 20
w = 200

medical_effect = "poison"
eff = 10
