object_type = "item"
id = "!weed3"
 
[image]
path = "weed3.png"
w = 24
h = 24

[icon]

[item]
gen_weight = 10
gen_level = 1
basic_price = 20

item_kind = "Food"
medical_effect= "Heal"
eff = 10
nutrition = 10
