object_type = "item"
id = "!weed3"
 
[image]
path = "weed3.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 10
gen_level = 1
basic_price = 20

medical_effect= "heal"
eff = 10
nutrition = 10
