object_type = "chara_template"
id = "!jelly"
 
[image]
path = "jelly.png"
w = 24
h = 48

[chara_template]
race = "Slime"
gen_weight = 10
gen_level = 1
max_hp = 14
str = 7
vit = 11
dex = 6
int = 8
wil = 5
cha = 12
spd = 50
