object_type = "chara_template"
id = "!merchant.m"
 
[image]
path = "merchant.m.png"
w = 24
h = 48

[chara_template]
race = "Human"
gen_weight = 0
gen_level = 0
max_hp = 120
str = 14
vit = 20
dex = 22
int = 20
wil = 11
cha = 17
spd = 100
