object_type = "chara_template"
id = "!"
 
[image]
path = "null.png"
w = 24
h = 48

[chara_template]
race = "Human"
gen_weight = 0
gen_level = 0
max_hp = 100
str = 42
vit = 42
dex = 42
int = 42
wil = 42
cha = 42
spd = 100
