object_type = "chara_template"
id = "fire-ant"
 
[image]
copyright="T.Okubo"
path = "fire-ant.png"
w = 24
h = 24

[chara_template]
race = "bug"
gen_weight = 80
gen_level = 15
default_ai_kind = "melee"
base_hp = 65
str = 17
vit = 16
dex = 13
int = 11
wil = 8
cha = 10
spd = 100
