object_type = "chara_template"
id = "scorpion"
 
[image]
copyright="T.Okubo"
path = "scorpion.png"
w = 32
h = 32

[chara_template]
race = "bug"
gen_weight = 10
gen_level = 20
default_ai_kind = "melee"
base_hp = 55
str = 16
vit = 15
dex = 14
int = 8
wil = 9
cha = 12
spd = 100
