object_type = "item"
id = "ancient-box"
 
[image]
copyright="T.Okubo"
path = "ancient-box.png"

[item]
item_kind = "special"
group = "ancient-box"
gen_weight = 0
gen_level = 0
basic_price = 100
w = 10000
