object_type = "item"
id = "deed-of-land"
 
[image]
copyright="T.Okubo"
path = "deed-of-land.png"

[item]
item_kind = "special"
group = "deed"
gen_weight = 0
gen_level = 0
basic_price = 1000
w = 5

[[item.use_effect.kind]]
kind = "deed"
