object_type = "item"
id = "boiled-potato"
 
[image]
path = "boiled-potato.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 0
shop_weight = 10
gen_level = 1
basic_price = 200
w = 300

nutrition = 200
