object_type = "item"
id = "bread"
 
[image]
copyright="T.Okubo"
path = "bread.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 10
shop_weight = 30
gen_level = 1
basic_price = 300
w = 200

nutrition = 200
