object_type = "item"
id = "butter"
 
[image]
copyright="T.Okubo"
path = "butter.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 1
shop_weight = 5
gen_level = 1
basic_price = 450
w = 150

nutrition = 150
