object_type = "item"
id = "cabbage"
 
[image]
copyright="T.Okubo"
path = "cabbage.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 0
shop_weight = 5
gen_level = 0
basic_price = 500
w = 400

nutrition = 70
