object_type = "item"
id = "canned-ration"
 
[image]
copyright="T.Okubo"
path = "canned-ration.png"

[item]
item_kind = "food"
group = "preserved-food"
gen_weight = 10
shop_weight = 10
gen_level = 1
basic_price = 500
w = 300

nutrition = 1000
