object_type = "item"
id = "carrot"
 
[image]
copyright="T.Okubo"
path = "carrot.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 1
shop_weight = 5
gen_level = 0
basic_price = 500
w = 200

nutrition = 70
