object_type = "item"
id = "cooking-oil"
 
[image]
path = "cooking-oil.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 1
shop_weight = 5
gen_level = 0
basic_price = 600
w = 150

nutrition = 150
