object_type = "item"
id = "cooking-oil"
 
[image]
copyright="T.Okubo"
path = "cooking-oil.png"

[item]
item_kind = "food"
group = "seasoning"
gen_weight = 1
shop_weight = 5
gen_level = 0
basic_price = 600
w = 150

nutrition = 150
