object_type = "item"
id = "corn"
 
[image]
copyright="T.Okubo"
path = "corn.png"

[item]
item_kind = "food"
group = "vegetable"
gen_weight = 1
shop_weight = 5
gen_level = 0
basic_price = 300
w = 350

nutrition = 120
