object_type = "item"
id = "failed-dish"
 
[image]
copyright="T.Okubo"
path = "failed-dish.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 0
shop_weight = 0
gen_level = 0
basic_price = 10
w = 200

nutrition = 10
