object_type = "item"
id = "french-fries"
 
[image]
path = "french-fries.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 0
shop_weight = 5
gen_level = 1
basic_price = 2000
w = 180

nutrition = 750
