object_type = "item"
id = "grape"
 
[image]
copyright="T.Okubo"
path = "grape.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 8
shop_weight = 10
gen_level = 0
basic_price = 100
w = 250

nutrition = 200
