object_type = "item"
id = "hard-biscuit"
 
[image]
copyright="T.Okubo"
path = "hard-biscuit.png"

[item]
item_kind = "food"
group = "preserved-food"
gen_weight = 5
shop_weight = 10
gen_level = 1
basic_price = 340
w = 80

nutrition = 700
