object_type = "item"
id = "honey"
 
[image]
copyright="T.Okubo"
path = "honey.png"

[item]
item_kind = "food"
group = "seasoning"
gen_weight = 2
shop_weight = 5
gen_level = 0
basic_price = 800
w = 120

nutrition = 1500
