object_type = "item"
id = "meat"
 
[image]
copyright="T.Okubo"
path = "meat.png"

[item]
item_kind = "food"
group = "meat"
gen_weight = 0
shop_weight = 10
gen_level = 0
basic_price = 800
w = 1000

nutrition = 1000
