object_type = "item"
id = "milk"
 
[image]
copyright="T.Okubo"
path = "milk.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 0
shop_weight = 5
gen_level = 0
basic_price = 500
w = 300

nutrition = 300
