object_type = "item"
id = "mochi"
 
[image]
copyright="T.Okubo"
path = "mochi.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 2
shop_weight = 1
gen_level = 1
basic_price = 2000
w = 100

nutrition = 1500
