object_type = "item"
id = "popcorn"
 
[image]
copyright="T.Okubo"
path = "popcorn.png"
w = 14
h = 19

[item]
item_kind = "food"
gen_weight = 0
shop_weight = 5
gen_level = 1
basic_price = 1500
w = 140

nutrition = 600
