object_type = "item"
id = "salt"
 
[image]
copyright="T.Okubo"
path = "salt.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 2
shop_weight = 5
gen_level = 0
basic_price = 2000
w = 50

nutrition = 10
