object_type = "item"
id = "tomato"
 
[image]
copyright="T.Okubo"
path = "tomato.png"

[item]
item_kind = "food"
group = "vegetable"
gen_weight = 0
shop_weight = 5
gen_level = 0
basic_price = 500
w = 200

nutrition = 200
