object_type = "item"
id = "turnip"
 
[image]
copyright="T.Okubo"
path = "turnip.png"
w = 24
h = 24

[item]
item_kind = "food"
gen_weight = 0
shop_weight = 5
gen_level = 0
basic_price = 300
w = 500

nutrition = 80
