object_type = "item"
id = "wheat-flour"
 
[image]
copyright="T.Okubo"
path = "wheat-flour.png"

[item]
item_kind = "food"
group = "vegetable"
gen_weight = 1
shop_weight = 50
gen_level = 0
basic_price = 300
w = 400

nutrition = 60
